version: 0.2
phases:
  install:
    pre_build:
      commands:
        # install dependencies
        - echo installing dependencies
        - npm install
        - echo dependencies successfully installed
    build:
      commands:
        - echo building
        - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
